# Generated by Django 5.1.7 on 2026-04-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0004_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordemdeservico',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordens de Serviço'},
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='descricao_problema',
            field=models.TextField(verbose_name='Descrição do Problema'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='esquadrilha',
            field=models.CharField(max_length=100, verbose_name='Esquadrilha'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='funcao',
            field=models.CharField(max_length=100, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='graduacao',
            field=models.CharField(max_length=50, verbose_name='Graduação'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='nome_guerra',
            field=models.CharField(max_length=100, verbose_name='Nome de Guerra'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='posto',
            field=models.CharField(max_length=50, verbose_name='Posto'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='status',
            field=models.CharField(default='Aberta', editable=False, max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='status_compra',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('negociado', 'Negociado'), ('entregue', 'Entregue'), ('disponivel', 'Disponível'), ('deferido', 'Deferido')], default='pendente', max_length=20, verbose_name='Status de Compra'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='telefone_contato',
            field=models.CharField(max_length=15, verbose_name='Telefone de Contato'),
        ),
        migrations.AlterField(
            model_name='ordemdeservico',
            name='tipo_servico',
            field=models.CharField(choices=[('notebook', 'Manutenção de Notebook'), ('computador', 'Manutenção de Microcomputador'), ('acesso', 'Controle de Acesso')], max_length=50, verbose_name='Tipo de Serviço'),
        ),
    ]
